version: '3.8'

services:
  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sort-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  sort-api:
    image: sort-api:latest
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: sort-api
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/sort-api
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SERVICE_INSTANCE_URLS: http://localhost:8081
      SERVER_PORT: 8080
      RESPONSE_DELAY_MEAN: 500
      RESPONSE_ERROR_PROBABILITY: 0.01
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
