# Deployment для Service A
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: sort-api-instance1
          image: elizaveta24/sort-api:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SPRING_APPLICATION_NAME_INSTANCE1
            - name: SERVICE_INSTANCE_URLS
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SERVICE_INSTANCE_URLS_INSTANCE1
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SERVER_PORT_INSTANCE1
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SPRING_DATASOURCE_URL_INSTANCE1
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sort-api-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sort-api-secret
                  key: SPRING_DATASOURCE_PASSWORD

---

# Deployment для Service B
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: sort-api-instance2
          image: elizaveta24/sort-api:latest
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SPRING_APPLICATION_NAME_INSTANCE2
            - name: SERVICE_INSTANCE_URLS
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SERVICE_INSTANCE_URLS_INSTANCE2
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SERVER_PORT_INSTANCE2
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SPRING_DATASOURCE_URL_INSTANCE2
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sort-api-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sort-api-secret
                  key: SPRING_DATASOURCE_PASSWORD

---

# Deployment для Service C
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
        - name: sort-api-instance3
          image: elizaveta24/sort-api:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SPRING_APPLICATION_NAME_INSTANCE3
            - name: SERVICE_INSTANCE_URLS
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SERVICE_INSTANCE_URLS_INSTANCE3
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SERVER_PORT_INSTANCE3
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: sort-api-config
                  key: SPRING_DATASOURCE_URL_INSTANCE3
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sort-api-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sort-api-secret
                  key: SPRING_DATASOURCE_PASSWORD
